# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ce0207dc32e42803f3347276ca4408050018429390fc584005ba1db9131cce28ea11003fe7b83c3c07085c56bbaec85bfac89b33b6de2b724e1991109a1c196

test:
  secret_key_base: 128cba6ff11e56d6fd2a33cb6971224a13b7a1bb344a6c8dc544c6f1193f4987099b957468b6783d4836d6c38bed98c18bc22d0f49a60f0d3a587c5934290a68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
